apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-config
  labels:
{{ include "puller.labels" . | indent 4 }}
data:
  images: {{ join "," .Values.puller.images | quote }}
  interval: {{ .Values.puller.interval | quote }}
  {{- if .Values.app.log.json }}
  jsonlog: {{ .Values.app.log.json | quote }}
  {{- end }}
  {{- if .Values.registry.server }}
  server: {{ .Values.registry.server | quote }}
  {{- end }}
