{{ if or .Values.registry.username .Values.registry.password }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-secret
  labels:
{{ include "puller.labels" . | indent 4 }}
data:
  {{- if .Values.registry.username }}
  username: {{ .Values.registry.username | b64enc }}
  {{- end }}
  {{- if .Values.registry.password }}
  password: {{ .Values.registry.password | b64enc }}
  {{- end }}
{{ end -}}